services:
  api:
    build:
      context: .
      dockerfile: ./AlbinRonnkvist.HybridSearch.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - webapp

  webapp:
    build:
      context: .
      dockerfile: ./AlbinRonnkvist.HybridSearch.WebApp/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development