services:
  api:
    build:
      context: .
      dockerfile: ./AlbinRonnkvist.HybridSearch.Api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=5000
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  webapp:
    build:
      context: .
      dockerfile: ./AlbinRonnkvist.HybridSearch.WebApp/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=80
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro