services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  api:
    build:
      context: .
      dockerfile: ./AlbinRonnkvist.HybridSearch.Api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=3000
      - ASPNETCORE_URLS=http://+:3000
    depends_on:
      - elasticsearch
    networks:
      - elastic
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  webapp:
    build:
      context: .
      dockerfile: ./AlbinRonnkvist.HybridSearch.WebApp/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=80
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - api
    networks:
      - elastic
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

networks:
  elastic:
    driver: bridge